require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - '**/*.pb.rb'
    - '**/*_pb.rb'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'client/**/*'
    - 'spec/dummy/db/schema.rb'
    - '**/node_modules/**/*'
  NewCops: enable

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '*.gemspec'
    - 'config/routes.rb'

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

# Enable the cop after it has learned to distinguish strftime.
# See https://github.com/bbatsov/rubocop/issues/5398
Style/FormatStringToken:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/ClassAndModuleChildren:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Naming/PredicateName:
  ForbiddenPrefixes:
    - is_
    - have_

RSpec/DescribeClass:
  Enabled: false

Performance/RedundantMerge:
  MaxKeyValuePairs: 1

# TODO: Cop is currently broken for `foo_bar1`. Re-enable once fixed.
# See https://github.com/bbatsov/rubocop/issues/3516
Naming/VariableNumber:
  Enabled: false

# Some RSpec cops are a bit excessive

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

# Enable cops that are inactive by default:

Style/SymbolArray:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/Send:
  Enabled: true

Style/StringMethods:
  Enabled: true

# brakeman currently cannot parse squiggly heredocs(i.e. <<~DOC)
Layout/HeredocIndentation:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false
